version: "3"

dotenv: [".env"]

vars:
  DATABASE_URL: "postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSLMODE}}"
  MIGRATION_DIR: "{{.MIGRATION_DIR}}"

tasks:
  migrate-create:
    desc: Create a new migration file
    cmds:
      - migrate create -ext sql -dir {{.MIGRATION_DIR}} -seq {{.NAME}}
    requires:
      vars: [NAME]

  migrate-up:
    desc: Apply all up migrations
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" up

  migrate-down:
    desc: Rollback the last migration
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" down 1

  migrate-down-n:
    desc: Rollback the last N migrations
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" down {{.N}}
    requires:
      vars: [N]

  migrate-force:
    desc: Force set the migration version without running migrations
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" force {{.VERSION}}
    requires:
      vars: [VERSION]

  migrate-drop:
    desc: Drop all tables and reset the database
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" drop

  migrate-goto:
    desc: Migrate to a specific version
    cmds:
      - migrate -path {{.MIGRATION_DIR}} -database "{{.DATABASE_URL}}" goto {{.VERSION}}
    requires:
      vars: [VERSION]
